# Generated by Django 2.2.4 on 2019-09-05 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('f_name', models.CharField(blank=True, max_length=100)),
                ('m_name', models.CharField(blank=True, max_length=100)),
                ('college_name', models.CharField(blank=True, max_length=100)),
                ('eno', models.CharField(blank=True, max_length=50)),
                ('course', models.CharField(blank=True, max_length=50)),
                ('branch', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female ', 'Female'), ('other', 'other')], default='Male', max_length=20)),
                ('rollno', models.IntegerField(blank=True, default=100)),
                ('year', models.CharField(blank=True, max_length=50)),
                ('sem', models.CharField(blank=True, max_length=50)),
                ('dob', models.DateField()),
                ('address', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_type', models.CharField(choices=[('News', 'ANNOUNCEMENTS/NOTICES/NEWS'), ('Tender ', 'Tenders'), ('Events', 'EVENTS/WORKSHOPS/CONFERENCES')], default='News', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
