# Generated by Django 2.2.4 on 2019-10-02 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_fee', models.IntegerField(blank=True, default=0)),
                ('portal_fee', models.IntegerField(blank=True, default=0)),
                ('late_fee', models.IntegerField(blank=True, default=0)),
                ('total_fee', models.IntegerField(blank=True, default=0)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('fname', models.CharField(blank=True, max_length=100)),
                ('college_name', models.CharField(blank=True, max_length=100)),
                ('branch', models.CharField(blank=True, max_length=50)),
                ('rollno', models.IntegerField(blank=True, default=100)),
                ('year', models.CharField(blank=True, max_length=50)),
                ('sem', models.CharField(blank=True, max_length=50)),
                ('dob', models.DateField()),
                ('session', models.CharField(blank=True, max_length=50)),
                ('stype', models.CharField(blank=True, max_length=50)),
                ('regulartyp', models.CharField(blank=True, max_length=50)),
                ('privatetyp', models.CharField(blank=True, max_length=50)),
                ('payment_status', models.CharField(default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_type', models.CharField(choices=[('News', 'Student Notice Board'), ('Events', 'Events / Workshops / Conferences'), ('other', 'Staff Notice Board')], default='News', max_length=20)),
                ('specifications', models.FileField(default='null', upload_to='router_specifications')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
