# Generated by Django 2.2.4 on 2019-09-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_fee',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
