# Generated by Django 2.2.4 on 2019-09-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='update_type',
            field=models.CharField(choices=[('News', 'ANNOUNCEMENTS/NOTICES/NEWS'), ('Tender ', 'Tenders'), ('Events', 'EVENTS/WORKSHOPS/CONFERENCES'), ('other', 'other')], default='News', max_length=20),
        ),
    ]
