# Generated by Django 2.2.4 on 2019-09-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_student_total_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
