# Generated by Django 2.2.4 on 2019-09-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190907_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stype',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
