# Generated by Django 2.2.4 on 2019-09-08 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_student_stype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
    ]
