# Generated by Django 2.2.4 on 2019-10-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('fname', models.CharField(blank=True, max_length=100)),
                ('enno', models.IntegerField(blank=True, default=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('attachment', models.FileField(default='null', upload_to='contactus')),
            ],
        ),
    ]
