# Generated by Django 2.2.4 on 2019-09-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_student_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sstype',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
