# Generated by Django 2.2.4 on 2019-09-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_student_sstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='specifications',
            field=models.FileField(default='null', upload_to='router_specifications'),
        ),
    ]
