# Generated by Django 2.2.4 on 2019-09-08 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_student_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='f_name',
            new_name='fname',
        ),
    ]
