# Generated by Django 2.1.5 on 2019-09-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='update_type',
            field=models.CharField(choices=[('News', 'Student Notice Board'), ('Tender ', 'Staff Notice Board'), ('Events', 'Events / Workshops / Conferences'), ('other', 'other')], default='News', max_length=20),
        ),
    ]
