# Generated by Django 2.2.4 on 2019-09-08 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190908_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='m_name',
            new_name='mname',
        ),
    ]
