# Generated by Django 2.1.5 on 2019-09-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190923_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='update_type',
            field=models.CharField(choices=[('News', 'Student Notice Board'), ('Events', 'Events / Workshops / Conferences'), ('other', 'Staff Notice Board')], default='News', max_length=20),
        ),
    ]
